mod day1;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod day10;
mod day11;
mod day12;
mod day13;

fn main() {
    println!("Day1:");
    day1::compute("data/Day1/main.txt");
    println!("Day2:");
    day2::compute("data/Day2/main.txt");
    println!("Day3:");
    day3::compute("data/Day3/main.txt");
    println!("Day4:");
    day4::compute("data/Day4/main.txt");
    println!("Day5:");
    day5::compute("data/Day5/main.txt");
    println!("Day6:");
    day6::compute("data/Day6/main.txt");
    println!("Day7:");
    day7::compute("data/Day7/main.txt");
    println!("Day8:");
    day8::compute("data/Day8/main.txt");
    println!("Day9:");
    day9::compute("data/Day9/main.txt");
    println!("Day10:");
    day10::compute("data/Day10/main.txt");
    println!("Day11:");
    day11::compute("data/Day11/main.txt");
    println!("Day12:");
    day12::compute("data/Day12/main.txt");
    println!("Day13:");
    day13::compute("data/Day13/main.txt");
}
